# Generated by Django 6.1.1 on 2026-09-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('name_acronym', models.CharField(max_length=4)),
                ('driver_number', models.IntegerField()),
                ('driver_team', models.CharField(max_length=200)),
                ('headshot_url', models.URLField()),
                ('team_colour', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('circuit_name', models.CharField(max_length=200)),
                ('flag_url', models.URLField()),
                ('session_key', models.IntegerField()),
                ('meeting_key', models.IntegerField()),
                ('circuit_short_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('results_fetched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('dnf', models.BooleanField(default=False)),
                ('dns', models.BooleanField(default=False)),
                ('dsq', models.BooleanField(default=False)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.driver')),
                ('meeting_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.race')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(null=True)),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p1_picks', to='league.driver')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2_picks', to='league.driver')),
                ('p3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p3_picks', to='league.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.race')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'race'), name='one_prediction_per_race')],
            },
        ),
    ]
