# Generated by Django 6.1.1 on 2026-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_rename_driver_name_result_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='headshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
